version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-pg!@1234}@postgres_r1:5432/${POSTGRES_DB:-clone_line_db}?sslmode=disable
      PORT: 8888
      MINIO_ENDPOINT: minio_r1:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-admin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio!@1234}
      MINIO_BUCKET: ${MINIO_BUCKET:-clone-line-uploads}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL:-http://gvbesaz3jj52upp8d3qnstp6.157.85.103.69.sslip.io}
    ports:
      - "8888:8888"
    networks:
      - public_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8888}
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8888}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - public_network

networks:
  public_network:
    driver: bridge
